re:
  gamemode: CREATIVE # при вводе /re {игрок}, админа телепортирует к игрку, и админа переводит в этот гейммод
  bans:
    command: "/tempban {0} {1} {2}"
    material: "BLAZE_POWDER" # материал предмета для бана
    prefix: "&#23dad7Забанить за &#FF0000{0}"
    color_of_reason: "&#FF0000" # цвет название предмета для бана в инвентаре, то есть в нашем случае "&#23dad7Забанить за &#FF0000читерство"
    #таких причин можно добавлять сколько хотите, главное чтобы инвентаря хватило ;)
    cheater:
      reason: "читерство"
      time: "1d" # это время подставляется в бан, тоесть при клике на предмет, вводиться команда от имени игрока /tempban {ник виновника} {эта переменная, тоесть time} {reason} в нашем случае напишеься /tempban {ник} читерство 1d
  items:
    compass:
      name: "&#23dad7Телепортироваться к игроку &#00FF00{0}"
      slot: 1
    recoil_stick:
      name: "&#23dad7Палка с отдачей"
      slot: 2
    through_walls:
      name: "&#23dad7Проходить сквозь стены"
      slot: 3
      material: "PRISMARINE_SHARD"
    checkcheater:
      name: "&#23dad7Вызвать на проверку читов"
      slot: 4
      material: "BLAZE_ROD"
    quit:
      name: "&#23dad7Выйти из наблюдения"
      slot: 9
      material: "BARRIER"

checkCheater:
  commandOnLeave: "/tempban {0} 1d выход во время проверки" # команда которая вводиться при выходе проверяемого (вводиться от имени администратора)

optimization:
  re_compass_track: true # будет ли компас следовать за "жертвой", в режиме следования
  throughwalls: true # включить ли прохождение сквозь стены