re:
  gamemode: CREATIVE
  bans:
    command: "/tempban {0} {1} {2}"
    material: "BLAZE_POWDER" # материал предмета для бана
    prefix: "&#23dad7Забанить за &#FF0000{0}"
    color_of_reason: "&#FF0000" # цвет название предмета для бана в инвентаре, то есть в нашем случае "&#23dad7Забанить за &#FF0000читерство"
    #таких причин можно добавлять сколько хотите, главное чтобы инвентаря хватило ;)
    cheater:
      reason: "читерство"
      time: "1d" # это время подставляется в бан, тоесть при клике на предмет, вводиться команда от имени игрока /tempban {ник виновника} {эта переменная, тоесть time} {reason} в нашем случае напишеься /tempban {ник} читерство 1d
  items:
    compass:
      name: "&#23dad7Телепортироваться к игроку &#00FF00{0}"
      slot: 1
    recoil_stick:
      name: "&#23dad7Палка с отдачей"
      slot: 2
    through_walls:
      name: "&#23dad7Проходить сквозь стены"
      slot: 3
      material: "PRISMARINE_SHARD"
    quit:
      name: "&#23dad7Выйти из наблюдения"
      slot: 9
      material: "BARRIER"