name: AdminAssist
version: '1.0-SNAPSHOT'
main: org.katok.adminAssist.Main
api-version: '1.16'

permissions:
  AdminAssist.re:
    default: op
  AdminAssist.throughwalls:
    default: op
  AdminAssist.checkCheat:
    default: op
  AdminAssist.spawnfakeore:
    default: op

commands:
  re:
    usage: /re
    permission: AdminAssist.re
  unre:
    usage: /unre
    permission: AdminAssist.re
  throughwalls:
    usage: /throughwalls
    permission: AdminAssist.throughwalls
  checkcheater:
    usage: /checkcheater
    permission: AdminAssist.checkCheat
  spawnfakeore:
    usage: "/spawnfakeore <ore> <count of ore> <seconds to respawn ore>"
    aliases: sfo
    permission: AdminAssist.spawnfakeore